services:
  nginx:
    image: nginx:latest
    container_name: blog-nginx
    restart: always
    networks:
      - blog
      - reverse-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`blog.jolly96dog.dev`)"
      - "traefik.http.routers.nginx.tls=true"
    volumes:
      - ./volume/nginx/data/redirect.conf:/etc/nginx/conf.d/default.conf
    tty: true

networks:
  blog:
    external: true
  reverse-proxy:
    external: true